apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-assets-pdb
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: assets