apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-assets
  namespace: {{ .Values.namespace }}
  labels:
    app: assets
    app.kubernetes.io/name: assets
    app.kubernetes.io/part-of: landing-pages
spec:
  type: ClusterIP
  selector:
    app: assets
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http