apiVersion: v1
kind: ServiceAccount
metadata:
  name: assets
  namespace: {{ .Values.namespace }}
  labels:
    app: assets
    app.kubernetes.io/name: assets
    app.kubernetes.io/part-of: landing-pages