apiVersion: v1
kind: ServiceAccount
metadata:
  name: editor
  namespace: {{ .Values.namespace }}
  labels:
    app: editor
    app.kubernetes.io/name: editor
    app.kubernetes.io/part-of: landing-pages