apiVersion: v1
kind: ServiceAccount
metadata:
  name: publisher
  namespace: {{ .Values.namespace }}
  labels:
    app: publisher
    app.kubernetes.io/name: publisher
    app.kubernetes.io/part-of: landing-pages