apiVersion: v1
kind: ServiceAccount
metadata:
  name: renderer
  namespace: {{ .Values.namespace }}
  labels:
    app: renderer
    app.kubernetes.io/name: renderer
    app.kubernetes.io/part-of: landing-pages