apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-renderer
  namespace: {{ .Values.namespace }}
  labels:
    app: renderer
    app.kubernetes.io/name: renderer
    app.kubernetes.io/part-of: landing-pages
spec:
  type: ClusterIP
  selector:
    app: renderer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http